# This is a basic workflow to help you get started with Actions

name: Checkout 

# Controls when the action will run. 
on:
  push:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          # persist-credentials: false
          ssh-key: ${{secrets.DEPLOY_SSH_KEY}}
          ssh-known-hosts: ${{secrets.SSH_HOSTS}} 
          ssh-strict: 'FALSE'
      - name: Update submodules with latest hash
        run: git submodule update --remote
      - name: Install Vercel cli
        run: yarn global add vercel
      - name: Deploy to Vercel (Production Deployment)
        if: github.ref != 'refs/heads/main'
        run: |
             echo DEPLOYMENT_URL="$(vercel --prod --token ${{secrets.VERCEL_TOKEN}} --env ENV_1=test --env ENV_2=test1 -env ENV_3=test2)"
      - name: Deploy to Vercel (Preview Deployment)
        if: github.ref == 'refs/heads/main'
        run: vercel --token ${{secrets.VERCEL_TOKEN}}
      - name: Create check     
        run: curl --location --request POST 'https://api.github.com/repos/k-lusine/next-intl/check-runs' --header "Accept:application/vnd.github.v3+json" --header 'Content-Type:application/json' --user 'k-lusine:${{secrets.GITHUB_TOKEN}}' --data-raw '{"name":"Preview Url", "status":"completed", "conclusion":"success", "head_sha":"${{github.sha}}","output":{"title":"Link is in the details","summary":"[Deployment Link]( ${{ env.DEPLOYMENT_URL }})"} }'